import "server-only";
import type { ReportType } from "@prisma/client";

/** A titled section of a generated report. */
export interface ReportSection {
  heading: string;
  body: string;
}

export interface GeneratedReport {
  title: string;
  sections: ReportSection[];
  markdown: string;
  provider: string;
  model: string;
}

/** Inputs the report composer draws from (all grounded in prior AI output). */
export interface ReportInputs {
  documentTitle: string;
  summary: {
    overview: string | null;
    purpose: string | null;
    background: string | null;
    decision: string | null;
    outcome: string | null;
  } | null;
  metadata: {
    court: string | null;
    caseNumber: string | null;
    judge: string | null;
    decisionDate: Date | null;
    acts: string[];
    sections: string[];
  } | null;
  provider: string;
  model: string;
}

const TITLES: Record<ReportType, string> = {
  EXECUTIVE: "Executive Report",
  CLIENT: "Client Report",
  COMPLIANCE: "Compliance Report",
  LEGAL_OPINION: "Legal Opinion",
};

function metadataSection(meta: ReportInputs["metadata"]): ReportSection | null {
  if (!meta) return null;
  const rows = [
    meta.court && `- **Court/Authority:** ${meta.court}`,
    meta.caseNumber && `- **Case Number:** ${meta.caseNumber}`,
    meta.judge && `- **Judge:** ${meta.judge}`,
    meta.decisionDate && `- **Date:** ${meta.decisionDate.toLocaleDateString()}`,
    meta.acts.length ? `- **Acts:** ${meta.acts.slice(0, 8).join("; ")}` : null,
    meta.sections.length ? `- **Sections:** ${meta.sections.slice(0, 12).join(", ")}` : null,
  ].filter(Boolean);
  if (rows.length === 0) return null;
  return { heading: "Key Details", body: rows.join("\n") };
}

const NA = "Not available in the analyzed content.";

/**
 * Compose a report deterministically from a document's existing AI intelligence
 * (executive summary + extracted metadata). Different report types emphasize
 * different sections. Everything is grounded in prior grounded output — the
 * composer never invents new facts.
 */
export function composeReport(type: ReportType, input: ReportInputs): GeneratedReport {
  const s = input.summary;
  const sections: ReportSection[] = [];

  switch (type) {
    case "EXECUTIVE":
      sections.push(
        { heading: "Overview", body: s?.overview ?? NA },
        { heading: "Purpose", body: s?.purpose ?? NA },
        { heading: "Background", body: s?.background ?? NA },
        { heading: "Decision", body: s?.decision ?? NA },
        { heading: "Outcome & Impact", body: s?.outcome ?? NA }
      );
      break;
    case "CLIENT":
      sections.push(
        { heading: "Summary", body: s?.overview ?? NA },
        { heading: "What This Means For You", body: s?.outcome ?? s?.decision ?? NA },
        { heading: "Context", body: s?.background ?? NA }
      );
      break;
    case "COMPLIANCE":
      sections.push(
        { heading: "Scope", body: s?.purpose ?? s?.overview ?? NA },
        {
          heading: "Applicable Provisions",
          body:
            input.metadata && (input.metadata.acts.length || input.metadata.sections.length)
              ? [
                  input.metadata.acts.length ? `Acts: ${input.metadata.acts.join("; ")}` : null,
                  input.metadata.sections.length ? `Sections: ${input.metadata.sections.join(", ")}` : null,
                ]
                  .filter(Boolean)
                  .join("\n")
              : NA,
        },
        { heading: "Key Determination", body: s?.decision ?? NA },
        { heading: "Compliance Impact", body: s?.outcome ?? NA }
      );
      break;
    case "LEGAL_OPINION":
      sections.push(
        { heading: "Facts", body: s?.background ?? NA },
        { heading: "Issue", body: s?.purpose ?? NA },
        { heading: "Analysis", body: s?.overview ?? NA },
        { heading: "Decision", body: s?.decision ?? NA },
        { heading: "Conclusion", body: s?.outcome ?? NA }
      );
      break;
  }

  const meta = metadataSection(input.metadata);
  if (meta) sections.push(meta);

  const title = `${TITLES[type]} — ${input.documentTitle}`;
  const markdown = renderMarkdown(title, sections);

  return { title, sections, markdown, provider: input.provider, model: input.model };
}

function renderMarkdown(title: string, sections: ReportSection[]): string {
  const header = `# ${title}\n\n_Generated by BriefVault on ${new Date().toLocaleDateString()}_\n\n> This report is AI-generated from the document's analysis and is not legal advice.\n`;
  const body = sections
    .map((sec) => `## ${sec.heading}\n\n${sec.body}\n`)
    .join("\n");
  return `${header}\n${body}`;
}
